import { IFormStructure } from "@shared/models/form";
import { RowData } from "@shared/models/table";

export const TerminalDetailsData: RowData = {
  "headers": [{ label: "Sr.No", key: "SR.NO", type: 'autoIncrementNumber', size: '4%' },
  { label: "Terminal Name", key: "terminal_name", type: '' },
  { label: "Code", key: "terminal_code", type: '' },
  { label: "City", key: "city_name", type: '' },
  { label: "State", key: "state_name", type: '' },
  { label: "Contact Person", key: "contact_person", type: '' },
  { label: "Number", key: "contact_number", type: '' },
  { label: "Email", key: "email", type: '' },
  { label: "Action", key: "action", type: 'action', size: '10%', buttonNames: ['edit', 'view', 'delete'] }],
  "data": [],
  "dataKey": 'terminal_id',
  "buttonname": 'Create Terminal',
  "button": true,
  "statuses": [
    { label: 'false', value: 'danger' },
    { label: 'true', value: 'success' },
  ],
  "filterfields": ['terminal_name'],
  "isSearch": false
}

export const TerminalTypeSearchGroup: IFormStructure[] = [
  {
    name: "terminal_id",
    placeholder: "Terminal Id",
    label: "Terminal  Id",
    type: "text",
    value: "",
    hiddenControl: true,
    disable: false,
  },
  {
    name: "terminal_name",
    label: "Terminal Name",
    placeholder: "Enter name",
    type: "text",
    value: "",
    required: true,
    isUpperCase: true,
    disable: false,
  },
  {
    name: "terminal_code",
    label: "Terminal Code",
    placeholder: "Enter code",
    type: "text",
    value: "",
    required: false,
    disable: false,
  },
  {
    name: "postal_code",
    label: "Postal Code",
    placeholder: "Enter Postal Code",
    type: "number",
    value: "",
    required: false,
    disable: false,
  },
  {
    name: "contact_person",
    label: "Contact Person Name",
    placeholder: "Enter Contact Person name",
    type: "text",
    value: "",
    required: false,
    disable: false,
  },
  {
    name: "contact_number",
    label: "Contact Number",
    placeholder: "Enter Contact Number",
    type: "number",
    value: "",
    validationFor: 'contact',
    required: false,
    disable: false,
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter Email",
    type: "text",
    value: "",
    validationFor: 'email',
    required: false,
    disable: false,
  },
  {
    name: "city_id",
    label: "City",
    placeholder: "Enter City",
    type: "select",
    value: "",
    required: true,
    disable: false,
    bindValue: 'city_id',
    bindLabel: 'city_name',
    listName: 'city',
    listData: []
  },
  {
    name: "state_id",
    label: "State",
    placeholder: "Enter State",
    type: "select",
    value: "",
    required: false,
    disable: false,
    bindValue: 'state_id',
    bindLabel: 'state_name',
    listName: 'state',
    listData: []
  },
  {
    name: "country_id",
    label: "Country",
    placeholder: "Enter Country",
    type: "select",
    value: "",
    required: true,
    disable: false,
    bindValue: 'country_id',
    bindLabel: 'country_name',
    listName: 'country',
    listData: []
  },
  {
    name: "address",
    label: "Terminal Address",
    placeholder: "Enter Terminal Address",
    type: "textarea",
    value: "",
    required: true,
    disable: false,
  },
]