import { IFormStructure } from "@shared/models/form";
import { RowData } from "@shared/models/table";

export const TerminalDetailsData: RowData = {
    "headers": [{ label: "Sr.No", key: "SR.NO", type: 'autoIncrementNumber', size: '4%' },
    { label: "Terminal Name", key: "terminalName", type: '' },
    { label: "Terminal Code", key: "terminalCode", type: '' },
    { label: "Action", key: "action", type: 'action', size: '8%', buttonNames: ['edit', 'view', 'delete'] }],
    "data": [],
    "dataKey": 'terminal_id',
    "buttonname": 'Create Terminal',
    "button": true,
    "statuses": [
        { label: 'false', value: 'danger' },
        { label: 'true', value: 'success' },
    ],
    "filterfields": ['terminalName'],
    "isSearch": false
}

export const TerminalTypeSearchGroup: IFormStructure[] = [
    {
        name: "terminal_id",
        placeholder: "Terminal Id",
        label: "Terminal  Id",
        type: "text",
        value: "",
        hiddenControl: true,
        disable: false,
    },
    {
        name: "terminal_name",
        label: "Terminal Name",
        placeholder: "Enter name",
        type: "text",
        value: "",
        required: true,
        isUpperCase: true,
        disable: false,
    },
    {
        name: "address",
        label: "Terminal Address",
        placeholder: "Enter Terminal Address",
        type: "text",
        value: "",
        required: true,
        disable: false,
    },
      {
        name: "country_id",
        label: "Country Id",
        placeholder: "Country Id",
        type: "text",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "state_id",
        label: "State id",
        placeholder: "State Id",
        type: "text",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "city_id",
        label: "City Id",
        placeholder: "City Id",
        type: "text",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "postal_code",
        label: "Postal Code",
        placeholder: "Enter Postal Code",
        type: "number",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "contact_person",
        label: "Contact Person Name",
        placeholder: "Enter Contact Person name",
        type: "text",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "contact_number",
        label: "Contact Number",
        placeholder: "Enter Contact Number",
        type: "number",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
      {
        name: "email",
        label: "Email",
        placeholder: "Enter Email",
        type: "email",
        value: "",
        required: false,
        isUpperCase: true,
        disable: false,
    },
]